### PR TITLE
README tweaks

### PR DESCRIPTION
**Pull request by mattleblanc**
Noted a couple of small inconsistencies while working through this, and also we need theano as well.

Thanks for writing this up, it is exactly what I was complaining about! In other news, I successfully got everything here to work without also completely scuttling my python3 install.

🍻 MLB

### CODE REVIEW

**Comment by dguest** [comment]
Hey @mattleblanc! 

Thanks for checking things and glad it works! Also thanks for fixing things, I'll merge this shortly, but I wanted to check a few things:

 - Does it still work if you run `pip3 uninstall theano; pip3 install tensorflow`? I don't really care what backend we use, but I'm currently running tensorflow and wanted to know if that works out of the box.
 - What you got against Dr Mc Jerkface?

**Comment by mattleblanc** [comment]
* Nope that breaks the thing, but this doesn't rule out that it just breaks because I am a troglodyte-esque 

* Our convenors are great people and i would describe none of them, particularly none who would be asking me for cross-checks, as a Dr McJerkface

**Comment by dguest** [comment]
If after two hours you look around the approval meeting and you don't see Convener McJerkface, you're Convener McJerkface.

 -- Mahatma Gandhi

**Comment by dguest** [comment]
@mattleblanc, I've managed to talk a few more people into trying this out and I have a question!

Can you show me what you get with

```
cat ~/.keras/keras.json
```

?

I'm a bit confused because it seems that most machines use the tensorflow backend by default, but for some reason you seem to be picking up theano. Have you ever edited that file before?

**Pull request merged**
